language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run predeploy
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
